language: csharp
sudo: required
dist: xenial

dotnet: 2.1.500

os:
  - linux

before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - sudo apt-get install -y powershell
  - sudo pwsh ./.psscripts/install-dotnet.ps1

script:
  - export PATH=/home/travis/.dotnetsdk:$PATH
  - pwsh ./build.ps1 -Release